---
kind: pipeline
type: docker
name: CD

steps:
  - name: build
    image: docker:19.03
    commands:
      - docker build . -t bipbeep:latest
    volumes:
      - name: docker
        path: /var/run/docker.sock