---
kind: pipeline
type: docker
name: CD

steps:
  - name: build
    image: docker:19.03
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - docker build . -t bipbeep:latest
  - name: deploy
    image: docker/compose:1.25.5
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - docker-compose -p bipbeep up -d frontend
    depends_on:
      - build
    when:
      event:
        - tag


volumes:
  - name: docker
    host:
      path: /var/run/docker.sock