version: '3'
services:
  frontend:
    build: .
    image: bipbeep:latest
    restart: always
    labels:
      - "traefik.frontend.rule=Host:bipbeep.cchampou.me"
      - "traefik.backend.port=5000"
      - "traefik.enable=true"
      - "traefik.docker.network=layko_layko_net"
  frontend-dev:
    build: .
    command: yarn dev
  database:
    image: mongo:3.6.18
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example



networks:
  default:
    external:
      name: layko_layko_net