version: '3'
services:
  frontend:
    build: frontend/.
    image: bipbeep:latest
    restart: always
    labels:
      - "traefik.frontend.rule=Host:bipbeep.cchampou.me"
      - "traefik.backend.port=5000"
      - "traefik.enable=true"
      - "traefik.docker.network=layko_layko_net"
  frontend-dev:
    build: frontend/.
    command: yarn dev
    expose:
      - "1234"
      - "33033"
    ports:
      - "1234:1234"
      - "33033:33033"
    volumes:
      - "./frontend/src:/usr/src/frontend/src"
  backend-dev:
    build: backend/.
    command: ls
    expose:
      - "1234"
      - "33033"
    ports:
      - "1234:1234"
      - "33033:33033"
    volumes:
      - "./frontend/src:/usr/src/frontend/src"
    depends_on:
      - database
  database:
    image: mongo:3.6.18
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example



networks:
  default:
    external:
      name: layko_layko_net